dependencies {
    compileOnly(libs.jetbrains.annotations)

    clientLocalRuntime(forge.jecharacters.get())

    // Recipe Viewers
    compileOnly(forge.bundles.jei)
//    compileOnly(forge.emi) // no 26.1 build
//    modCompileOnly(forge.jer)

    // Mekanism (jarjar embedded)
    jarJar(forge.mekanism)
    jarJar(forge.mekanism.additions)
    jarJar(forge.mekanism.generators)
    jarJar(forge.mekanism.tools)

    compileOnly(forge.mekanism)
    compileOnly(forge.mekanism.additions)
    compileOnly(forge.mekanism.generators)
    compileOnly(forge.mekanism.tools)

//    compileOnly(forge.mekanismcovers)
//    compileOnly(forge.evolvedmekanism)

    // FTB
//    compileOnly(forge.architectury)

//    compileOnly(forge.ftblibrary)
//    compileOnly(forge.ftbultimine)

    // Crt
//    compileOnly(forge.crt)

    // mysticalAgriculture
//    compileOnly(forge.mysticalagriculture)

    // immersiveengineering
//    compileOnly(forge.immersiveengineering)

    // CC: Tweaked
//    compileOnly(forge.cc.tweaked.core.api)
//    compileOnly(forge.cc.tweaked.forge.api)

    // WAILA-likes
    compileOnly(forge.jade)

    // Standard runtime mods //
    localRuntime(forge.jade)
    localRuntime(forge.modernfix)
    localRuntime(forge.ferritecore)

    // Mekanism
    localRuntime(forge.mekanism)
    localRuntime(forge.mekanism.additions)
    localRuntime(forge.mekanism.generators)
    localRuntime(forge.mekanism.tools)

//    localRuntime(forge.mekanismcovers)
//    localRuntime(forge.igleelibrary)
//    localRuntime(forge.evolvedmekanism)

    // FTB //
//    localRuntime(forge.architectury)
//    localRuntime(forge.ftblibrary)
//    localRuntime(forge.ftbultimine)

    // Crt
//    localRuntime(forge.crt)

    // mysticalAgriculture
//    localRuntime(forge.cucumber)
//    localRuntime(forge.mysticalagriculture)

    // immersiveengineering
//    localRuntime(forge.immersiveengineering)

    // Runtime Recipe Viewers - uncomment whichever one you want to use //
//    modLocalRuntime(forge.jer)
//    modLocalRuntime(forge.emi)
    localRuntime(forge.jei.neoforge.impl)

    // Client-only runtime mods //
    clientLocalRuntime(forge.sodium)
//    clientLocalRuntime(forge.iris)
//    clientLocalRuntime(forge.modernui) // not yet for 26.1

    //////////////////////////////////////////////////////
    // Runtime mods for dev testing with unclean client //
    //////////////////////////////////////////////////////
}