[versions]
minecraft = "26.1.2"
neoForge = "26.1.2.36-beta"
loader = "4"
parchment = "2025.12.20" # https://parchmentmc.org/docs/getting-started
shadow = "9.4.1"
spotless = "8.4.0"
modDevGradle = "2.0.141"
lombok = "9.5.0"
jetbrains-annotations = "26.0.1"
mixin = "0.8.7"

[libraries]
minecraft               = { module = "com.mojang:minecraft", version.ref = "minecraft" }
neoForge                = { module = "net.neoforged:neoforge", version.ref = "neoForge" }
jetbrains-annotations   = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }

[plugins]
modDevGradle            = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
shadow                  = { id = "com.gradleup.shadow", version.ref = "shadow" }
spotless                = { id = "com.diffplug.spotless", version.ref = "spotless" }
lombok                  = { id = "io.freefair.lombok", version.ref = "lombok" }
